# create environment : conda env create -f conda_env.yml
# update dependencies: conda env update -f conda_env.yml
# remove environment : conda env remove -n mintpy
# enter  environment : conda activate mintpy
# exit   environment : conda deactivate
name: minsar
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - isce2
  - basemap
  - bokeh
  - boto3
  - botocore
  - cdsapi
  - git
  - natsort
  - psycopg2
  - pycurl
#### from ../sources/MintPy/docs/conda_env.yml  except basemap
  - dask>=1.0,<2.0
  - dask-jobqueue>=0.3,<1.0
  - ecCodes
  - h5py
  - lxml
  - matplotlib
  - netcdf4
  - numpy
  - openmp
  - pip
  - pygrib
  - pyhdf
  - pykdtree
  - pyproj
  - pyresample
  - scikit-image
  - scipy
  - pip:
    - opencv-python
    - geocoder
#    - git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
    - git+https://github.com/tylere/pykml.git
