# create environment : conda env create -f conda_env.yml
# update dependencies: conda env update -f conda_env.yml
# remove environment : conda env remove -n mintpy
# enter  environment : conda activate mintpy
# exit   environment : conda deactivate
name: minsar
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - isce2
  - cdsapi
  - git
  - psycopg2
  - pycurl
  - natsort
  - bokeh
  - boto3
  - botocore
  - basemap
  - pip:
    - opencv-python
    - geocoder
#    - git+https://github.com/matplotlib/basemap.git#egg=mpl_toolkits
    - git+https://github.com/tylere/pykml.git
